### ISSUE TITLE
Missing sqlite code

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/aisRX_pi#1]
This plugin uses the ShipDriver template.
objsearch_pi has a template but is not a managed plugin. I have not been able to find other examples.
aisRX needs to access the EU River Information Services database, This is now an sqlite file.
Need to add sqlite to the libraries in the plugin.

Edit: Going to use one of the other libraries as a start.

**Comment by Rasbats** [comment]
[https://github.com/utelle/wxsqlite3](https://github.com/utelle/wxsqlite3)
Is the way I want to go.

**Comment by Rasbats** [comment]
sqlite-amalgamation-3360000 is the latest version.

**Comment by leamas** [comment]
> https://github.com/utelle/wxsqlite3 is the way to go

perhaps, perhaps not. The question is if your plugin depends on sqlite3 or wxSqlite. If it only requries sqlite3 it makes no sense to pull in wxSqlite. OTOH, it might be a dependency. Can you check?

**Comment by leamas** [comment]
The sqlite3 sources lives at https://sqlite.org/src/doc/trunk/README.md. This is what we should use if it's a plain sqlite3 dependency.

**Comment by leamas** [comment]
At a glance, I find no references to sqlite in these sources. Am I missing something, or is it something you plan to implement?

**Comment by Rasbats** [comment]
objsearch_pi with sqlite-amalgamation-3360000 seems to give good access to the database without the overhead of the full sqlite source. 

The RIS index is needed as the plugin develops. The signals/objects on the canals have a code but no lat/lon. The RIS index allows the location of all the objects.

Reading the ais message it is possible to locate the object on the chart and show the state of the signal/water level etc.

Another use for (wx)sqlite would be for updating the opencpn survey plugin. At the moment it is Windows only.

**Comment by leamas** [comment]
Now, let's take this one plugin at a time. Adding a library is no big deal really, and we should use whatever best in the specific plugins.

So, talking about this very plugin, since I don't find any references to sqlite: Is it something I miss, or is this something you plan to implement?

**Comment by leamas** [comment]
> objsearch_pi with sqlite-amalgamation-3360000 seems to give good access to the database without the overhead of the full sqlite source.

No, the amalgamation *is* the full source, it's just that they have concatenated it into a single file. We could use the amalgamation  (single file, ~185 KLOC) or the about 100 source files, it is basically the same thing. However, compiling such a large file needs a lot of memory when compiling which could spell trouble in some cases.

**Comment by leamas** [comment]
wxSqlite is a layer on top of sqlite, so sqlite is needed in any case here. There is a sqlite lib in OpenCPN which we probably could use as is (it is based on the amalgamation, though, and needs an update anyway).

**Comment by Rasbats** [comment]
Added the wxSqlite and amalgamation from objsearch. It compiles on windows. Now in Github.

**Comment by leamas** [comment]
This is actually not how this is supposed to be done. New libs like sqlite and wxsqliyt (which effectiveluy is what this is all about) should live in libs/ and have their separate CMakeLists and a link target. It's about the programming overall effort to separate things.

**Comment by Rasbats** [comment]
Yes ... my limited knowledge leads me down these alleyways.

**Comment by leamas** [comment]
You have a PR for sqlite, I'll se what I can do with wxSqlite later. 

Here is also tons of compiler warnings to take care of. It should compile cleanly, really.

**Comment by Rasbats** [comment]
Thanks. One of the problems with the latest wxSqlite may be the encryption stuff, requiring sqlite 3.36.

**Comment by leamas** [comment]
Well, updating sqlite shouldn't be that complicated. But the core issue is: do you need wxsqlite? If I understand this correctly, it provides some string conversions + encryption. Are these features enough to motivate yet another dependency?

Why don't you just start with just sqlite, and wait with wxsqlite until you know it's required?

**Comment by leamas** [comment]
Anyway, you have a PR also for wxsqlite

**Comment by leamas** [comment]
While on it, I also have a pending PR for updating sqlite to 3.37. However, I'm  a lazy programmer and waits until you have merged or rejected #3.

**Comment by Rasbats** [comment]
Thanks again. PR for wxsqlite merged.
> But the core issue is: do you need wxsqlite?

Seems to be a lazy way for accessing my database.

**Comment by Rasbats** [comment]
Problem with compiling the wxSqlite3 lib. It can't find sqlite3.h it needs to compile wxSqlite3.cpp.

**Comment by leamas** [comment]
Compiles for me. Can you submit a link to the build?

**Comment by leamas** [comment]
wait... I can reproduce that, I think. Hang on...

**Comment by leamas** [comment]
OK, I can reproduce this locally (I got away with a quick check since sqlite3.h was available globally). I'll look into it, but no time right now. Back later.

**Comment by leamas** [comment]
Back on chair. The sqlite3.h include is fixed, but here are more serious trouble with wxSqlite. Let's see if/how it can be dealt with.

**Comment by leamas** [comment]
OK. Recent versions of wxSqlite bundles it own, outdated copy of sqlite. The arrangement is clumsy enough to make me suspicious.

Conclusions:
  - Using wxSqlite means using an bundled, outdated copy of sqlite3.
  - It is not possible to use a fresh sqlite3 version in the same build as one using wxsqlite
  - Which means that we must choose between wxsqlite and plain sqlite3.

sqlite3 is a very well maintained library with a lot of users.It is also used as-is in main OpenCPN.  IMHO one need string reasons to not use the upstream sources in such a case. Do we have such string reasons to use wxSqlite?

**Comment by leamas** [comment]
BTW: I forgot to mention the patch which was about sqlite3.h  not found. Comes below, it's a plain bug-fix to apply:

```
diff --git a/libs/sqlite/CMakeLists.txt b/libs/sqlite/CMakeLists.txt
index 8f97f0d..3529784 100644
--- a/libs/sqlite/CMakeLists.txt
+++ b/libs/sqlite/CMakeLists.txt
@@ -21,7 +21,7 @@ if (NOT SQLITE_FOUND OR NOT USE_SYSTEM_SQLITE)
   )
   target_link_libraries(_SQLITE INTERFACE SQLITE3)
   target_include_directories(
-    _SQLITE INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include
+    SQLITE3 PUBLIC ${CMAKE_CURRENT_LIST_DIR}/include
   )
 
   # We do not need extensions, and using them in a static library
diff --git a/libs/wxsqlite/CMakeLists.txt b/libs/wxsqlite/CMakeLists.txt
index 12e819a..21e36c5 100644
--- a/libs/wxsqlite/CMakeLists.txt
+++ b/libs/wxsqlite/CMakeLists.txt
@@ -16,4 +16,5 @@ add_library(_WXSQLITE STATIC ${SRC})
 target_include_directories(
   _WXSQLITE PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include
 )
+target_link_libraries(_WXSQLITE PRIVATE sqlite::sqlite)
 add_library(wxsqlite::wxsqlite ALIAS _WXSQLITE)

```

**Comment by Rasbats** [comment]
> Do we have such string reasons to use wxSqlite?

I had reached the same conclusion. Don't spend any more time on wxSqlite. I have used sqlite3 directly with survey_pi. This is the new route.

**Comment by Rasbats** [comment]
Getting the data out of my RIS database. I will upgrade sqlite3 tomorrow and test. Thanks for the help with the library this will be a benefit to other plugins.

**Comment by leamas** [comment]
OK. You meed to apply the patch above to sqlite/CMakeLists.txt anyway, it's a plain bug to fix.

**Comment by leamas** [comment]
I added the bugfix patch to the pending PR

**Comment by Rasbats** [comment]
Just about to update sqlite. Closing.
